// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskBook_Entity_CodeFirst.Model;

namespace TaskBook_Entity_CodeFirst.Migrations
{
    [DbContext(typeof(TaskBookContext))]
    partial class TaskBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskBook_Entity_CodeFirst.Model.Deadline", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Deadlines");
                });

            modelBuilder.Entity("TaskBook_Entity_CodeFirst.Model.Priority", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Prioritys");
                });

            modelBuilder.Entity("TaskBook_Entity_CodeFirst.Model.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("TaskBook_Entity_CodeFirst.Model.TaskBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeadlineID")
                        .HasColumnType("int");

                    b.Property<int?>("PrioritiesID")
                        .HasColumnType("int");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeadlineID");

                    b.HasIndex("PrioritiesID");

                    b.HasIndex("StatusID");

                    b.ToTable("TaskBooks");
                });

            modelBuilder.Entity("TaskBook_Entity_CodeFirst.Model.TaskBook", b =>
                {
                    b.HasOne("TaskBook_Entity_CodeFirst.Model.Deadline", "Deadline")
                        .WithMany("TaskBooks")
                        .HasForeignKey("DeadlineID");

                    b.HasOne("TaskBook_Entity_CodeFirst.Model.Priority", "Priorities")
                        .WithMany("TaskBooks")
                        .HasForeignKey("PrioritiesID");

                    b.HasOne("TaskBook_Entity_CodeFirst.Model.Status", "Status")
                        .WithMany("TaskBooks")
                        .HasForeignKey("StatusID");
                });
#pragma warning restore 612, 618
        }
    }
}
